### ISSUE TITLE
Achieve transition between 2 faces, without defining points .

### ISSUE THREAD

**Issue by YeisonVelez11** [jembezmamy/morpher-js#16]
Hello, I congratulate you for your great library. I am trying to achieve this effect:
Https://upload.wikimedia.org/wikipedia/commons/a/a7/Morphvideo-ape-bird-april12-2015.ogv
But I need to upload 2 images and this animation is generated. This would be done automatically then I need to skip the part of defining points. How can I skip this part, or what can I use?

**Comment by jembezmamy** [comment]
Hello, you could try to use a face detection software to determine important points i.e. eyes, nose, mouth and then use this data to programmatically construct a mesh required by MorpherJS (check out the "Defining mesh with API" section on the [demos page](http://jembezmamy.github.io/morpher-js/demos.html)).
If you have any questions about MorpherJS, please reopen this issue.

**Comment by YeisonVelez11** [comment]
Sorry for my ignorance, but first of all, I do not know how to make your code work. I see different .haml extensions. And with all my heart, can I ask you a small example of what you just explained to me? The truth I do not understand "Defining mesh with API" I would like an example of how it would be the configuration with a human face, it is somewhat confusing this example. This could help me Https://trackingjs.com/examples/face_hello_world.html. I must use some other library to achieve the morph effect from the client side. Thank you very much!

**Comment by jembezmamy** [comment]
Please follow [this instruction](https://github.com/jembezmamy/morpher-js#usage) to setup MorpherJS. Haml files are not relevant in your case, just download the [morpher.js file](http://jembezmamy.github.io/morpher-js/javascripts/morpher/morpher.js) and include it on your page.

I think it'd be a good idea to try a simple case first - i.e. pick 2 images, setup them manually and try to achieve satisfactory results.

Then you could try to manually simulate automatic face recognition. Just use face recognition software and relying on its results manually setup mesh for MorpherJS. This way you'll get an idea of possibilities this method gives you without investing too much work. Looking at the tracking.js I'd say it's not precise enough to get a good morphing effect. But you can try it and judge yourself - maybe it's suitable in your case.

If these results are good enough for you, you could try to integrate MorpherJS with a face recognition library. You'll have to use geometry data returned by this library to setup MorpherJS mesh programmatically (that means you'll have to write a program that performs the same procedure as you've performed in the previous paragraph).

The API section describes how to setup the mesh with a JavaScript code instead of drawing it manually. I won't provide an example for you because I've got no time today for this and tomorrow I'm going on vacation. Please try the above procedure to simply check if MorpherJS is a good choice for your project.
